spring:
  ai:
    #ollama:
    openai:
      #base-url: ${OLLAMA_URL:http://localhost:11434}
      base-url: ${VLLM_URL:http://localhost:8000}
      api-key: dummy
      chat:
        options:
          #model: llama3.1:8b
          model: Qwen/Qwen3-0.6B
          temperature: 0.8
    mcp:
      client:
        enabled: true
        type: SYNC
        initialized: true
        sse:
          connections:
            mcp-server:
              url: ${MCP_SERVER_URL:http://localhost:8081}
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG
    org.springframework.ai.openai: DEBUG
    org.springframework.web.client: TRACE