spring:
  elasticsearch:
    uris: ${ELASTIC_URL:http://localhost:9200}
  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      chat:
        options:
          #model: gemma3:12b
          model: llama3.1:8b
          temperature: 0.8
      model: mxbai-embed-large
    mcp:
      client:
        enabled: true
        type: SYNC
        initialized: true
        sse:
          connections:
            mcp-server:
              url: http://localhost:8081
#    vectorstore:
#      elasticsearch:
#        initialize-schema: true
#        index-name: custom-index
#        dimensions: 1024
#        similarity: cosine
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG